USE [master]
GO

/****** Object:  Database [projects]    Script Date: 7/7/2025 16:34:14 ******/
CREATE DATABASE [projects]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'projects', FILENAME = N'C:\Programs\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\projects.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'projects_log', FILENAME = N'C:\Programs\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\projects_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [projects].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [projects] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [projects] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [projects] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [projects] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [projects] SET ARITHABORT OFF 
GO

ALTER DATABASE [projects] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [projects] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [projects] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [projects] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [projects] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [projects] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [projects] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [projects] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [projects] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [projects] SET  ENABLE_BROKER 
GO

ALTER DATABASE [projects] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [projects] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [projects] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [projects] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [projects] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [projects] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [projects] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [projects] SET RECOVERY FULL 
GO

ALTER DATABASE [projects] SET  MULTI_USER 
GO

ALTER DATABASE [projects] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [projects] SET DB_CHAINING OFF 
GO

ALTER DATABASE [projects] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [projects] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [projects] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [projects] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [projects] SET QUERY_STORE = ON
GO

ALTER DATABASE [projects] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [projects] SET  READ_WRITE 
GO

